language: rust

cache: cargo

before_cache: |
  cargo install cargo-update  || echo "cargo-update already installed"
  cargo install cargo-audit  || echo "cargo-audit already installed"
  cargo install-update --all
# before_cache:
#     - rm -rf /home/travis/.cargo/registry

rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

script: |
  cargo clean
  cargo build
  cargo test
  # it's enough to run this once:
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo audit
  fi
